- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: Main-Group
    name: test-vm
    admin_username: michael
    admin_password: "${vm.password}"
    image:
      offer: Ubuntu Server
      publisher: Canonical
      sku: '18.04-LTS'
      version: latest